GET http://localhost:5000/user


###
GET http://localhost:5000/user

###
POST http://localhost:5000/api/v1/user/create
Content-Type: application/json

{
    "email": "testuser2@gmail.com",
    "password": "pashword",
    "owner": false
}

###
POST http://localhost:5000/api/v1/user/login
Content-Type: application/json

{
    "email": "testa@gmail.com",
    "password": "pashword"
}

